Simplify some of the `match` expression usages
- Replace `match ... { Ok(v) => Ok(v), Err(v) => ...}` with
  `.or_else()` combinator.
- Replace `match`es with single match arm with `if let` or `if`.
- Change rep()'s first argument type from String to &str.
- Introduce a boilerplate function rep_or_panic() for simplified error
  processing and better error reporting:
  (before) thread 'main' panicked at 'unexpected EOF', src/stepA_mal.rs:448
  (after)  thread 'main' panicked at 'rep on `(def! *host-language* "rust+wasm"("`
           failed at src/stepA_mal.rs:445: unexpected EOF', ...